SELECT CUSTOMERS.CID, CUSTOMERS.FIRST_NAME || ' ' || CUSTOMERS.LAST_NAME AS NAME FROM CUSTOMERS
INNER JOIN PURCHASES ON PURCHASES.CID = CUSTOMERS.CID
WHERE PURCHASES.PAYMENT = (
    SELECT MAX(PAYMENT)
    FROM PURCHASES
);