SELECT CUSTOMERS.CID, CUSTOMERS.FIRST_NAME, SUM(PURCHASES.PAYMENT) AS "total amount spent"
FROM CUSTOMERS
INNER JOIN PURCHASES ON CUSTOMERS.CID = PURCHASES.CID
GROUP BY CUSTOMERS.CID, CUSTOMERS.FIRST_NAME
ORDER BY "total amount spent" DESC
FETCH FIRST 4 ROWS ONLY;
