SELECT CUSTOMERS.CID
FROM customers 
JOIN PURCHASES ON CUSTOMERS.CID = PURCHASES.CID
JOIN PRODUCTS ON PURCHASES.PID = PRODUCTS.PID
WHERE CUSTOMERS.LAST_VISIT_DATE BETWEEN TO_DATE('01-AUG-2022', 'DD-MON-YYYY') AND TO_DATE('31-AUG-2022', 'DD-MON-YYYY')
  AND PRODUCTS.ORIG_PRICE BETWEEN 15 AND 20
GROUP BY CUSTOMERS.CID
HAVING COUNT(DISTINCT PRODUCTS.PID) = (
    SELECT COUNT(*) FROM PRODUCTS WHERE ORIG_PRICE BETWEEN 15 AND 20
);
