SELECT PRODUCTS.PID, PRODUCTS.NAME
FROM PRODUCTS
INNER JOIN PURCHASES ON PRODUCTS.PID = PURCHASES.PID
GROUP BY PRODUCTS.PID, PRODUCTS.NAME
ORDER BY (SYSDATE - MAX(PURCHASES.PUR_TIME)) DESC
FETCH FIRST 1 ROW ONLY;


