SELECT PRODUCTS.PID, PRODUCTS.NAME, SUM(PURCHASES.QUANTITY) AS "total quantity sold"
FROM PRODUCTS
INNER JOIN PURCHASES ON PRODUCTS.PID = PURCHASES.PID
GROUP BY PRODUCTS.PID, PRODUCTS.NAME
HAVING SUM(PURCHASES.QUANTITY) = (
    SELECT MAX(SUM_QUANTITY)
    FROM (
        SELECT SUM(QUANTITY) AS SUM_QUANTITY
        FROM PURCHASES
        GROUP BY PID
    ) 
);
