SELECT PRODUCTS.PID, PRODUCTS.NAME, 
       (PRODUCTS.ORIG_PRICE * PROD_DISCNT.DISCNT_RATE) AS "discount amount"
FROM PRODUCTS
INNER JOIN PROD_DISCNT ON PRODUCTS.DISCNT_CATEGORY = PROD_DISCNT.DISCNT_CATEGORY
WHERE (PRODUCTS.ORIG_PRICE * PROD_DISCNT.DISCNT_RATE) = (
    SELECT MAX(PRODUCTS.ORIG_PRICE * PROD_DISCNT.DISCNT_RATE)
    FROM PRODUCTS
    INNER JOIN PROD_DISCNT ON PRODUCTS.DISCNT_CATEGORY = PROD_DISCNT.DISCNT_CATEGORY
);
