SELECT DISTINCT(PRODUCTS.PID), PRODUCTS.NAME
FROM PRODUCTS
INNER JOIN PURCHASES ON PURCHASES.PID = PRODUCTS.PID
INNER JOIN EMPLOYEES ON EMPLOYEES.EID = PURCHASES.EID
WHERE (ORIG_PRICE > 180) AND 
(EMPLOYEES.NAME LIKE 'A%' OR EMPLOYEES.NAME LIKE 'D%');


