SELECT PRODUCTS.PID, PRODUCTS.NAME FROM PRODUCTS
INNER JOIN PURCHASES ON PURCHASES.PID = PRODUCTS.PID
WHERE (UNIT_PRICE < 10) AND (PUR_TIME BETWEEN TO_DATE('01-OCT-22', 'DD-MON-YY') AND TO_DATE('31-OCT-22', 'DD-MON-YY') OR PUR_TIME BETWEEN TO_DATE('01-DEC-2022', 'DD-MON-YY') AND TO_DATE('31-DEC-22'));



