SELECT CUSTOMERS.CID, CUSTOMERS.FIRST_NAME, COUNT(DISTINCT PURCHASES.PID) AS "Number of Different Products"
FROM CUSTOMERS
INNER JOIN PURCHASES ON CUSTOMERS.CID = PURCHASES.CID
GROUP BY CUSTOMERS.CID, CUSTOMERS.FIRST_NAME;
