SELECT EMPLOYEES.EID, EMPLOYEES.NAME FROM EMPLOYEES
WHERE EID NOT IN(
    SELECT PURCHASES.EID FROM PURCHASES
);



SELECT EMPLOYEES.EID, EMPLOYEES.NAME FROM EMPLOYEES
WHERE NOT EXISTS(
    SELECT 1 FROM PURCHASES
    WHERE PURCHASES.EID = EMPLOYEES.EID
);

