SELECT EMPLOYEES.EID, EMPLOYEES.NAME
FROM EMPLOYEES
/*LEFT JOIN PURCHASES ON EMPLOYEES.EID = PURCHASES.EID
INNER JOIN PRODUCTS ON PRODUCTS.PID = PURCHASES.PID
INNER JOIN PROD_DISCNT ON PROD_DISCNT.DISCNT_CATEGORY = PRODUCTS.DISCNT_CATEGORY*/
INNER JOIN PURCHASES ON EMPLOYEES.EID = PURCHASES.EID
INNER JOIN PRODUCTS ON PRODUCTS.PID = PURCHASES.PID
WHERE PRODUCTS.DISCNT_CATEGORY = 3
GROUP BY EMPLOYEES.EID, EMPLOYEES.NAME
HAVING COUNT(DISTINCT PRODUCTS.PID) = (
    SELECT COUNT(DISTINCT PID)
    FROM PRODUCTS
    WHERE DISCNT_CATEGORY = 3
);