SELECT PUR# FROM PURCHASES
INNER JOIN CUSTOMERS ON PURCHASES.CID = CUSTOMERS.CID
INNER JOIN PRODUCTS ON PRODUCTS.PID = PURCHASES.PID
INNER JOIN EMPLOYEES ON EMPLOYEES.EID = PURCHASES.EID
WHERE ((CUSTOMERS.FIRST_NAME LIKE 'K%' AND ORIG_PRICE < 15) AND TELEPHONE# LIKE '888%');



