SELECT PROD_DISCNT.DISCNT_CATEGORY AS DCT, PROD_DISCNT.DISCNT_RATE AS DCR
FROM PROD_DISCNT
LEFT JOIN PRODUCTS ON PRODUCTS.DISCNT_CATEGORY = PROD_DISCNT.DISCNT_CATEGORY
WHERE PRODUCTS.DISCNT_CATEGORY IS NULL;


